### ISSUE TITLE
Migration from Manifest v2 to Manifest v3

### ISSUE THREAD

**Issue by suyogkokaje** [Suhaan-Bhandary/Celebrate-LeetCode#1]
[Manifest v2 support timeline](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)

According to the above referred link, in 2023 Manifest v3 is prerequisite for the extensions. The current Manifest version of the extension is v3. So the migration from v2 to v3 is necessary.

**Comment by Suhaan-Bhandary** [comment]
I think it can be easily done, but some inbuilt function may not work, and will need refactor

Do you want to contribute for migrating?

**Comment by suyogkokaje** [comment]
Actually I tried to unpack the extension in the brave, it restricted me from doing that because of deprecated v2. Then I did some searching on google and did the necessary changes for the migration. But I was not able to solve the below issue I got after doing all the changes.

[Click here to see the issue](https://ibb.co/nCqZz1D)

**Comment by suyogkokaje** [comment]
Actually I tried to unpack the extension in brave but it restricted me from doing so because of deprecated v2. So I did the necessary changes for the migration, but I was not able to solve the following error.

[Click here to see the error](https://ibb.co/nCqZz1D)

**Comment by Suhaan-Bhandary** [comment]
Solved the issue!!, in the new version
